# Generated by Django 4.2.6 on 2023-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CASE_NUMBER',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='EMPLOYER_PROVINCE',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='JOB_TITLE',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='WORKSITE_POSTAL_CODE',
            field=models.CharField(max_length=30),
        ),
    ]
