from django.db import models

# Create your models here.
class Company(models.Model):
    CASE_NUMBER = models.CharField(primary_key=True, max_length=15)
    CASE_STATUS = models.CharField(max_length=100)
    CASE_SUBMITTED = models.DateField()  
    DECISION_DATE = models.DateField()  
    VISA_CLASS = models.CharField(max_length=20)
    EMPLOYMENT_START_DATE = models.DateField()  
    EMPLOYMENT_END_DATE = models.DateField()  
    EMPLOYER_NAME = models.CharField(max_length=80)
    EMPLOYER_ADDRESS = models.CharField(max_length=100)
    EMPLOYER_CITY = models.CharField(max_length=30)
    EMPLOYER_STATE = models.CharField(max_length=10)
    EMPLOYER_POSTAL_CODE = models.IntegerField()
    EMPLOYER_COUNTRY = models.CharField(max_length=30)
    EMPLOYER_PROVINCE = models.CharField(max_length=60)
    EMPLOYER_PHONE = models.BigIntegerField()
    EMPLOYER_PHONE_EXT = models.CharField(max_length=10)
    AGENT_ATTORNEY_NAME = models.CharField(max_length=20)
    AGENT_ATTORNEY_CITY = models.CharField(max_length=20)
    AGENT_ATTORNEY_STATE = models.CharField(max_length=10)
    JOB_TITLE = models.CharField(max_length=60)
    SOC_CODE = models.CharField(max_length=20)
    SOC_NAME = models.CharField(max_length=50)
    NAIC_CODE = models.BigIntegerField()
    TOTAL_WORKERS = models.IntegerField()
    FULL_TIME_POSITION = models.CharField(max_length=10)
    PREVAILING_WAGE = models.DecimalField(max_digits=20, decimal_places=2)
    PW_UNIT_OF_PAY = models.CharField(max_length=10) 
    PW_WAGE_SOURCE = models.CharField(max_length=10)
    PW_SOURCE_YEAR = models.IntegerField()
    PW_SOURCE_OTHER = models.CharField(max_length=30)
    WAGE_RATE_OF_PAY_FROM = models.DecimalField(max_digits=20, decimal_places=2)
    WAGE_RATE_OF_PAY_TO = models.DecimalField(max_digits=20, decimal_places=2)
    WAGE_UNIT_OF_PAY = models.CharField(max_length=10)
    HB = models.CharField(max_length=10)
    WILLFUL_VIOLATOR = models.CharField(max_length=10)
    WORKSITE_CITY = models.CharField(max_length=20)
    WORKSITE_COUNTY = models.CharField(max_length=20)
    WORKSITE_STATE = models.CharField(max_length=10)
    WORKSITE_POSTAL_CODE = models.CharField(max_length=30)
    ORIGINAL_CERT_DATE = models.DateField()  

